### ISSUE TITLE
orderNumber in wirecard seamless

### ISSUE THREAD

**Issue by gabrieladeniji** [hakito/php-wirecard-checkout-seamless#3]
Hello, 
Can't find orderNumber in my frontend/init.inc.php, needing it do some backend operation, how can I get my orderNumber?
please help.

**Comment by hakito** [comment]
This repo is just a convenience wrapper library around the wirecard checkout seamless api which is more object oriented and has PHPDoc. As far as I know the order number has to be generated by yourself. For further question please contact wirecard directly.

**Comment by gabrieladeniji** [comment]
Thanks for the reply, really appreciate it.

**Comment by gabrieladeniji** [comment]
Thanks for the heads up.
